version: "3"
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    command: mongod --auth
